### ISSUE TITLE
Vereinfachte Glättung (für den Abstand zum Noise Floor)

### ISSUE THREAD

**Issue by nFrechen** [fablabcb/CitRad-SensorUnit#12]
Für mean_amplitude und mean_amplitude_reverse eine vereinfachte Glättung implementieren:

[ZeileL136](https://github.com/fablabcb/CitRad-SensorUnit/blob/f25d952b29f67de85f0642ad1039cd40328ee163/Software/sensor/AudioSystem.cpp#L136) in AudioSystem::Results::process

mean_amplitude_runmean[i] = ((n-1) * mean_amplitude_runmean[i-1] + mean_amplitude)/n

mit n=100

Der geglättete Wert kann mit in die csv gespeichert werden.

Ergebnis als `dynamic_noise_level` speichern. Eingabewert n als `noise_dynamic_smoothing_factor` benennen.

**Comment by thorondev** [comment]
Config Value: "dynamicNoiseSmoothingFactor"
CSV Values: "dynamic_noise_level" und "dynamic_noise_level_reverse"
