### ISSUE TITLE
weitere Datenauswertung

### ISSUE THREAD

**Issue by nFrechen** [fablabcb/CitRad-SensorUnit#14]
Ich habe die Auswertemethode nun in [Software/data processing method/data_processing_method.Rmd](https://github.com/fablabcb/CitRad-SensorUnit/blob/main/Software/data%20processing%20method/data_processing_method.Rmd) beschrieben.

Zu beachten in R:

- Der Array Index beginnt bei 1 und nicht bei 0
- Wenn `v` ein Vektor ist dann  kann man in R `v*2` rechnen, wodurch jedes Element im Array mit 2 multipliziert wird. Genauso kann man die Elemente von zwei gleich langen Vektoren Element zu Element miteinander verrechnen mit `v*w`. Man braucht hier also keine Schleife.
- `apply` Funktionen arbeiten ähnlich wie `map` Funktionen in anderen Sprachen. Damit kann man z.B. eine Matrix in Zeilen zerschneiden und eine Funktion auf jede Zeile anwenden.

Am besten gehen wir gemeinsam durch den Code und überlegen wie wir das Stück für Stück umsetzen können.

**Comment by thorondev** [comment]
Aktueller Stand liegt auf dem Develop.
