### ISSUE TITLE
Fehler in metrics csv

### ISSUE THREAD

**Issue by nFrechen** [fablabcb/CitRad-SensorUnit#16]
- Spalte "car_trigger_signal_31" ist leer
- Spalte zwischen den beiden hat keinen Namen: `meanAmplitudeForNoiseLevel, , dynamic_noise_level_100`
- "binsWithSignal" und "binsWithSignal_reverse" sind immer 0. Die können wahrscheinlich aber auch ganz raus.

**Comment by thorondev** [comment]
Leere Spalte car_trigger_signal kam nur durch überflüssiges Komma zustande. Fixed.
